#!/usr/bin/env bash

# Variable Declarations
curdir="../PySlope/"
wdir="/usr/local/PySlope"
bin="${wdir}/bin"
cmd="export PATH=\"/usr/local/PySlope/bin:\$PATH\""
version=2.0


if [[ "$1" == "-h" ]]; then
	echo "
Usage: ./setup [-h] [-u] --Setup Options for PySlope v${version}

	where:
		-h    Shows this help message
		-u    Uninstalls all relevant data 

		*no argument     
		      Installs relevant data to appropriate folders

			"

elif [[ "$1" == "-u" ]]; then
	echo "Removing all related contents"
	rm -rf $wdir
	if [ "$(uname)" == "Darwin" ]; then
    # Do something under Mac OS X platform
        rm -rf /usr/local/share/man/man1/fos.1.gz
    elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
        rm -rf /usr/local/man/man1/fos.1.gz

    fi
elif [[ $# -eq 0 ]]; then
    ./setup -u
    if [ "$(uname)" == "Darwin" ]; then
    # Do something under Mac OS X platform
        install man/fos.1 /usr/local/share/man/man1/
        gzip /usr/local/share/man/man1/fos.1
    elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
        install man/fos.1 /usr/local/man/man1/
        gzip /usr/local/man/man1/fos.1
    fi
    rm -rf $wdir
	# Copy entire directory to seperate directory in /usr/local
	echo "Making Directory: /PySlope/"
	mkdir $wdir
	echo "Copying Content to: /usr/local/PySlope"
	cp -R $curdir $wdir
	# Make /usr/local/slope-stability/bin executable
	echo "Writing executable"
	chmod +x "$bin/fos"
	# Add /usr/local/slope-stability/bin to user PATH
	if grep /usr/local/slope-stability ~/.bash_profile; then
		:
	else
		echo "Adding link to \$PATH"
		echo $cmd >> ~/.bash_profile
	fi

	source ~/.bash_profile

	echo "PySlope Installed Successfully"
	echo "man fos - for more details"
else
	echo 'Unrecognised argument; try ./setup -h'
fi